In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib.inline

In [3]:
df = pd.DataFrame({"Age":np.random.randint(1,100,10)})
df
print("ini aku")

Age
0   69
1   78
2   48
3    1
4   48
5   85
6   56
7   95
8   29
9   17

In [2]:
import pandas as pd
import numpy as np
c = np.array([[1,2,3,4,5], [2,3,4,5,6], [20,30,40,50,60]])
print(c)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [20 30 40 50 60]]


In [30]:
c[:,2]

array([ 3,  4, 40])

In [32]:
c[1:3,3]

array([ 5, 50])

In [33]:
a = np.array([[[1,2,3,4,5], [2,3,4,5,6], [20,30,40,50,60]], [[1,2,3,4,5], [2,3,4,5,6], [200,300,400,500,600]]])
print(a)

[[[  1   2   3   4   5]
  [  2   3   4   5   6]
  [ 20  30  40  50  60]]

 [[  1   2   3   4   5]
  [  2   3   4   5   6]
  [200 300 400 500 600]]]


In [35]:
a.ndim

3

In [36]:
a[0:,:,1]

array([[  2,   3,  30],
       [  2,   3, 300]])

In [37]:
a[1,1,1:4]

array([3, 4, 5])

In [38]:
a[0,1:,1:3]

array([[ 3,  4],
       [30, 40]])

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [41]:
np.arange(0,10, dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros((2,5), dtype= int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
np.linspace(2, 10, 5, dtype= int)

array([ 2,  4,  6,  8, 10])

In [50]:
np.linspace(0,10,5, retstep=True)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)

In [58]:
a = np.linspace(0,10,7, retstep=True)
a

(array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
         8.33333333, 10.        ]),
 1.6666666666666667)

In [60]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [65]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
np.eye(10, k=3)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
np.eye(10, k=-3)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [75]:
np.diag(range(1,6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [76]:
np.full((10,10),144)

array([[144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144],
       [144, 144, 144, 144, 144, 144, 144, 144, 144, 144]])

In [79]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[4,8,3],[1,4,55]])
c = np.stack((a,b))
c

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 4,  8,  3],
        [ 1,  4, 55]]])

In [80]:
c.ndim

3

In [81]:
d = np.vstack((a,b))
d

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 4,  8,  3],
       [ 1,  4, 55]])

In [82]:
d.ndim

2

In [83]:
e = np.hstack((a,b))
e

array([[ 1,  2,  3,  4,  8,  3],
       [ 3,  4,  5,  1,  4, 55]])

In [85]:
np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  4,  8,  3],
       [ 3,  4,  5,  1,  4, 55]])

In [89]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
 

In [90]:
np.random.rand(2,3)

array([[0.86583833, 0.73832048, 0.10377234],
       [0.1748991 , 0.74764346, 0.47414941]])

In [92]:
np.random.randn(2,3)

array([[ 0.45847738, -1.28346115,  0.01415639],
       [ 0.08472968,  0.94192061,  0.64336335]])

In [98]:
np.random.randint(0,8, size=(2,3))

array([[0, 0, 1],
       [6, 7, 6]])

In [100]:
np.random.ranf((2,3))

array([[0.70683121, 0.22406128, 0.18413425],
       [0.45975051, 0.15997838, 0.44219696]])

In [102]:
a = np.random.rand(2,3)
a

array([[0.7582821 , 0.64813557, 0.72772187],
       [0.76651527, 0.50847288, 0.88871707]])

In [104]:
a.reshape((3,2))

array([[0.7582821 , 0.64813557],
       [0.72772187, 0.76651527],
       [0.50847288, 0.88871707]])

In [106]:
a.T

array([[0.7582821 , 0.76651527],
       [0.64813557, 0.50847288],
       [0.72772187, 0.88871707]])

In [116]:
a = np.random.rand(8,8)
a

array([[0.84235104, 0.76651178, 0.79981828, 0.49612625, 0.65240429,
        0.72152562, 0.10596899, 0.68840168],
       [0.87089315, 0.85629809, 0.97341005, 0.56322682, 0.39043174,
        0.05942891, 0.89661074, 0.23478016],
       [0.22971116, 0.14240742, 0.94401282, 0.66809249, 0.44305884,
        0.74111358, 0.14764713, 0.59286185],
       [0.56160041, 0.96734941, 0.32629204, 0.65891546, 0.76959828,
        0.59060363, 0.64110829, 0.92208381],
       [0.86352244, 0.67393766, 0.18492328, 0.22236567, 0.44387193,
        0.82296705, 0.61573747, 0.51699527],
       [0.83052037, 0.53449455, 0.37866622, 0.09293558, 0.90208089,
        0.91144209, 0.51250523, 0.13133191],
       [0.71602885, 0.10867792, 0.06132222, 0.67584979, 0.42424545,
        0.73576967, 0.63703235, 0.36472885],
       [0.85956066, 0.39574112, 0.85402437, 0.55384376, 0.31925969,
        0.62262705, 0.92612072, 0.05830993]])

In [120]:
d = a.reshape(2,2,2,2,2,2)
d

array([[[[[[0.84235104, 0.76651178],
           [0.79981828, 0.49612625]],

          [[0.65240429, 0.72152562],
           [0.10596899, 0.68840168]]],


         [[[0.87089315, 0.85629809],
           [0.97341005, 0.56322682]],

          [[0.39043174, 0.05942891],
           [0.89661074, 0.23478016]]]],



        [[[[0.22971116, 0.14240742],
           [0.94401282, 0.66809249]],

          [[0.44305884, 0.74111358],
           [0.14764713, 0.59286185]]],


         [[[0.56160041, 0.96734941],
           [0.32629204, 0.65891546]],

          [[0.76959828, 0.59060363],
           [0.64110829, 0.92208381]]]]],




       [[[[[0.86352244, 0.67393766],
           [0.18492328, 0.22236567]],

          [[0.44387193, 0.82296705],
           [0.61573747, 0.51699527]]],


         [[[0.83052037, 0.53449455],
           [0.37866622, 0.09293558]],

          [[0.90208089, 0.91144209],
           [0.51250523, 0.13133191]]]],



        [[[[0.71602885, 0.10867792],
           [0.06132222, 0.67584

In [121]:
d.ndim

6

In [124]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.resize(a, (3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
a = np.random.randint(2,10, size=(10,10,10))
a

array([[[5, 8, 6, 2, 4, 9, 8, 7, 4, 4],
        [4, 4, 8, 5, 2, 4, 8, 7, 3, 5],
        [6, 5, 7, 6, 5, 6, 2, 5, 9, 4],
        [2, 3, 2, 6, 8, 5, 4, 5, 7, 4],
        [9, 3, 2, 2, 7, 2, 4, 4, 4, 9],
        [3, 2, 4, 6, 6, 6, 6, 4, 5, 7],
        [9, 2, 2, 7, 8, 2, 5, 9, 5, 9],
        [5, 6, 5, 3, 9, 9, 4, 4, 4, 3],
        [9, 9, 8, 9, 3, 8, 4, 7, 3, 6],
        [3, 4, 7, 7, 5, 4, 7, 9, 9, 7]],

       [[7, 6, 9, 6, 5, 7, 4, 2, 2, 8],
        [4, 9, 3, 2, 5, 5, 5, 8, 5, 9],
        [9, 3, 3, 5, 3, 3, 7, 4, 8, 5],
        [7, 5, 5, 8, 8, 5, 9, 2, 4, 4],
        [9, 7, 5, 4, 4, 4, 9, 9, 6, 6],
        [9, 5, 9, 9, 6, 3, 6, 3, 5, 9],
        [5, 9, 5, 7, 3, 5, 2, 7, 3, 4],
        [5, 9, 9, 7, 3, 4, 7, 2, 5, 6],
        [9, 8, 2, 4, 7, 3, 8, 3, 2, 9],
        [5, 4, 3, 9, 9, 8, 8, 2, 9, 2]],

       [[3, 9, 8, 3, 2, 7, 9, 3, 5, 9],
        [4, 2, 2, 7, 8, 2, 5, 2, 9, 5],
        [6, 4, 2, 9, 3, 5, 8, 2, 9, 9],
        [6, 7, 8, 7, 3, 2, 9, 2, 2, 5],
        [9, 2, 4, 6, 5, 2, 3, 4, 7, 

In [131]:
a.flatten()

array([5, 8, 6, 2, 4, 9, 8, 7, 4, 4, 4, 4, 8, 5, 2, 4, 8, 7, 3, 5, 6, 5,
       7, 6, 5, 6, 2, 5, 9, 4, 2, 3, 2, 6, 8, 5, 4, 5, 7, 4, 9, 3, 2, 2,
       7, 2, 4, 4, 4, 9, 3, 2, 4, 6, 6, 6, 6, 4, 5, 7, 9, 2, 2, 7, 8, 2,
       5, 9, 5, 9, 5, 6, 5, 3, 9, 9, 4, 4, 4, 3, 9, 9, 8, 9, 3, 8, 4, 7,
       3, 6, 3, 4, 7, 7, 5, 4, 7, 9, 9, 7, 7, 6, 9, 6, 5, 7, 4, 2, 2, 8,
       4, 9, 3, 2, 5, 5, 5, 8, 5, 9, 9, 3, 3, 5, 3, 3, 7, 4, 8, 5, 7, 5,
       5, 8, 8, 5, 9, 2, 4, 4, 9, 7, 5, 4, 4, 4, 9, 9, 6, 6, 9, 5, 9, 9,
       6, 3, 6, 3, 5, 9, 5, 9, 5, 7, 3, 5, 2, 7, 3, 4, 5, 9, 9, 7, 3, 4,
       7, 2, 5, 6, 9, 8, 2, 4, 7, 3, 8, 3, 2, 9, 5, 4, 3, 9, 9, 8, 8, 2,
       9, 2, 3, 9, 8, 3, 2, 7, 9, 3, 5, 9, 4, 2, 2, 7, 8, 2, 5, 2, 9, 5,
       6, 4, 2, 9, 3, 5, 8, 2, 9, 9, 6, 7, 8, 7, 3, 2, 9, 2, 2, 5, 9, 2,
       4, 6, 5, 2, 3, 4, 7, 5, 4, 5, 9, 6, 8, 8, 9, 2, 4, 2, 3, 6, 9, 3,
       2, 8, 2, 3, 6, 8, 5, 3, 9, 6, 2, 6, 2, 3, 3, 7, 4, 7, 4, 4, 6, 8,
       9, 3, 9, 7, 3, 8, 2, 7, 3, 2, 7, 8, 6, 7, 6,

In [132]:
a.ravel()

array([5, 8, 6, 2, 4, 9, 8, 7, 4, 4, 4, 4, 8, 5, 2, 4, 8, 7, 3, 5, 6, 5,
       7, 6, 5, 6, 2, 5, 9, 4, 2, 3, 2, 6, 8, 5, 4, 5, 7, 4, 9, 3, 2, 2,
       7, 2, 4, 4, 4, 9, 3, 2, 4, 6, 6, 6, 6, 4, 5, 7, 9, 2, 2, 7, 8, 2,
       5, 9, 5, 9, 5, 6, 5, 3, 9, 9, 4, 4, 4, 3, 9, 9, 8, 9, 3, 8, 4, 7,
       3, 6, 3, 4, 7, 7, 5, 4, 7, 9, 9, 7, 7, 6, 9, 6, 5, 7, 4, 2, 2, 8,
       4, 9, 3, 2, 5, 5, 5, 8, 5, 9, 9, 3, 3, 5, 3, 3, 7, 4, 8, 5, 7, 5,
       5, 8, 8, 5, 9, 2, 4, 4, 9, 7, 5, 4, 4, 4, 9, 9, 6, 6, 9, 5, 9, 9,
       6, 3, 6, 3, 5, 9, 5, 9, 5, 7, 3, 5, 2, 7, 3, 4, 5, 9, 9, 7, 3, 4,
       7, 2, 5, 6, 9, 8, 2, 4, 7, 3, 8, 3, 2, 9, 5, 4, 3, 9, 9, 8, 8, 2,
       9, 2, 3, 9, 8, 3, 2, 7, 9, 3, 5, 9, 4, 2, 2, 7, 8, 2, 5, 2, 9, 5,
       6, 4, 2, 9, 3, 5, 8, 2, 9, 9, 6, 7, 8, 7, 3, 2, 9, 2, 2, 5, 9, 2,
       4, 6, 5, 2, 3, 4, 7, 5, 4, 5, 9, 6, 8, 8, 9, 2, 4, 2, 3, 6, 9, 3,
       2, 8, 2, 3, 6, 8, 5, 3, 9, 6, 2, 6, 2, 3, 3, 7, 4, 7, 4, 4, 6, 8,
       9, 3, 9, 7, 3, 8, 2, 7, 3, 2, 7, 8, 6, 7, 6,